### ISSUE TITLE
No events listeners appears

### ISSUE THREAD

**Issue by eimantaaas** [spatie/laravel-dashboard-oh-dear-uptime-tile#2]
I don't if I'm doing it wrong or something is not good, but when Oh dear pushes webhook to the site nothing happens. Then I looked at Laravel Telescope Request and I see that it fires `ohdear-webhooks::uptimeCheckFailed` event, but it says that there is no event listeners.

So I added these two events listeners to my `EventServiceProvider` to temporary fix this issue:

`Event::listen('ohdear-webhooks::uptimeCheckFailed', '\Spatie\OhDearUptimeTile\OhDearWebhooksEventSubscriber@onUptimeCheckFailed');`
`Event::listen('ohdear-webhooks::uptimeCheckRecovered', '\Spatie\OhDearUptimeTile\OhDearWebhooksEventSubscriber@onUptimeCheckRecovered');`

**Comment by freekmurze** [comment]
Do you reach this code? (maybe put a dd statement there)
https://github.com/spatie/laravel-dashboard-oh-dear-uptime-tile/blob/master/src/OhDearWebhooksEventSubscriber.php#L33

If not, could you check if the service provider of the package gets loaded?

**Comment by eimantaaas** [comment]
No, I can't reach this dd statement at this place

If I put dd statement here, I reach it
https://github.com/spatie/laravel-dashboard-oh-dear-uptime-tile/blob/master/src/OhDearUptimeTileServiceProvider.php#L16

**Comment by freekmurze** [comment]
I've found the problem, and fixed it in 1.0.2
