### ISSUE TITLE
Wrong type of variable

### ISSUE THREAD

**Issue by eimantaaas** [spatie/laravel-dashboard-oh-dear-uptime-tile#3]
When trying to mark site as up this issue comes up.

Argument 1 passed to `Spatie\OhDearUptimeTile\OhDearUptimeStore::Spatie\OhDearUptimeTile\{closure}()` must be of the type array, string given

changing this line
https://github.com/spatie/laravel-dashboard-oh-dear-uptime-tile/blob/master/src/OhDearUptimeStore.php#L38

to
`$downSites = array_filter($downSites, fn ($downSite) => $downSite !== $upSiteUrl);`

solves the issue.

**Comment by freekmurze** [comment]
Thanks for brining this to my attention. It is now fixed in the latest release.
